config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :agencies, :skip => [:registrations]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :agency_user do
    root 'admin/homes#index', as: :agency_user
  end
end

app/models/agency.rb
class Agency < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<div class="container">
  <div class="row">
    <h1>Welcome to Site</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterSetGo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if current_agency.present? %>
        <li class="nav-item">
          <%= link_to destroy_agency_session_path, method: :delete, class: 'sign-out-top-nav dropdown-item' do %>
            <i class="fas fa-sign-out-alt"></i> <%=t :logout %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_agency_session_path, class: 'sign-out-top-nav dropdown-item' do %>
            <i class="fas fa-sign-out-alt"></i> <%=t :login %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>